namespace AOC2020.Utilities
{
    using System.Collections.Generic;
    using System.Linq;

    public class DataFixture
    {
        private readonly List<PuzzleData> _puzzleData;

        public DataFixture()
        {
            PuzzleDataStore puzzleDataStore = new PuzzleDataStore();

            _puzzleData = new ()
            {
                new PuzzleData("01", "Actual", puzzleDataStore.GetPuzzleInputAsList("01"), puzzleDataStore.GetPuzzleAnswer("01", "1"), puzzleDataStore.GetPuzzleAnswer("01", "2"), string.Empty, false),
                new PuzzleData("02", "Actual", puzzleDataStore.GetPuzzleInputAsList("02"), puzzleDataStore.GetPuzzleAnswer("02", "1"), puzzleDataStore.GetPuzzleAnswer("02", "2"), string.Empty, false),
                new PuzzleData("03", "Actual", puzzleDataStore.GetPuzzleInputAsList("03"), puzzleDataStore.GetPuzzleAnswer("03", "1"), puzzleDataStore.GetPuzzleAnswer("03", "2"), string.Empty, false),
                new PuzzleData("04", "Actual", puzzleDataStore.GetPuzzleInputAsList("04"), puzzleDataStore.GetPuzzleAnswer("04", "1"), puzzleDataStore.GetPuzzleAnswer("04", "2"), string.Empty, false),
                new PuzzleData("05", "Actual", puzzleDataStore.GetPuzzleInputAsList("05"), puzzleDataStore.GetPuzzleAnswer("05", "1"), puzzleDataStore.GetPuzzleAnswer("05", "2"), string.Empty, false),
                new PuzzleData("06", "Actual", puzzleDataStore.GetPuzzleInputAsList("06"), puzzleDataStore.GetPuzzleAnswer("06", "1"), puzzleDataStore.GetPuzzleAnswer("06", "2"), string.Empty, false),
                new PuzzleData("07", "Actual", puzzleDataStore.GetPuzzleInputAsList("07"), puzzleDataStore.GetPuzzleAnswer("07", "1"), puzzleDataStore.GetPuzzleAnswer("07", "2"), string.Empty, false),
                new PuzzleData("08", "Actual", puzzleDataStore.GetPuzzleInputAsList("08"), puzzleDataStore.GetPuzzleAnswer("08", "1"), puzzleDataStore.GetPuzzleAnswer("08", "2"), string.Empty, false),
                new PuzzleData("09", "Actual", puzzleDataStore.GetPuzzleInputAsList("09"), puzzleDataStore.GetPuzzleAnswer("09", "1"), puzzleDataStore.GetPuzzleAnswer("09", "2"), string.Empty, false),
                new PuzzleData("10", "Actual", puzzleDataStore.GetPuzzleInputAsList("10"), puzzleDataStore.GetPuzzleAnswer("10", "1"), puzzleDataStore.GetPuzzleAnswer("10", "2"), string.Empty, false),
                new PuzzleData("11", "Actual", puzzleDataStore.GetPuzzleInputAsList("11"), puzzleDataStore.GetPuzzleAnswer("11", "1"), puzzleDataStore.GetPuzzleAnswer("11", "2"), string.Empty, false),
                new PuzzleData("12", "Actual", puzzleDataStore.GetPuzzleInputAsList("12"), puzzleDataStore.GetPuzzleAnswer("12", "1"), puzzleDataStore.GetPuzzleAnswer("12", "2"), string.Empty, false),
                new PuzzleData("13", "Actual", puzzleDataStore.GetPuzzleInputAsList("13"), puzzleDataStore.GetPuzzleAnswer("13", "1"), puzzleDataStore.GetPuzzleAnswer("13", "2"), string.Empty, false),
                new PuzzleData("14", "Actual", puzzleDataStore.GetPuzzleInputAsList("14"), puzzleDataStore.GetPuzzleAnswer("14", "1"), puzzleDataStore.GetPuzzleAnswer("14", "2"), string.Empty, false),
                new PuzzleData("15", "Actual", puzzleDataStore.GetPuzzleInputAsList("15"), puzzleDataStore.GetPuzzleAnswer("15", "1"), puzzleDataStore.GetPuzzleAnswer("15", "2"), string.Empty, false),
                new PuzzleData("16", "Actual", puzzleDataStore.GetPuzzleInputAsList("16"), puzzleDataStore.GetPuzzleAnswer("16", "1"), puzzleDataStore.GetPuzzleAnswer("16", "2"), string.Empty, false),
                new PuzzleData("17", "Actual", puzzleDataStore.GetPuzzleInputAsList("17"), puzzleDataStore.GetPuzzleAnswer("17", "1"), puzzleDataStore.GetPuzzleAnswer("17", "2"), string.Empty, false),
                new PuzzleData("18", "Actual", puzzleDataStore.GetPuzzleInputAsList("18"), puzzleDataStore.GetPuzzleAnswer("18", "1"), puzzleDataStore.GetPuzzleAnswer("18", "2"), string.Empty, false),
                new PuzzleData("19", "Actual", puzzleDataStore.GetPuzzleInputAsList("19"), puzzleDataStore.GetPuzzleAnswer("19", "1"), puzzleDataStore.GetPuzzleAnswer("19", "2"), string.Empty, false),
                new PuzzleData("20", "Actual", puzzleDataStore.GetPuzzleInputAsList("20"), puzzleDataStore.GetPuzzleAnswer("20", "1"), puzzleDataStore.GetPuzzleAnswer("20", "2"), string.Empty, false),
                new PuzzleData("21", "Actual", puzzleDataStore.GetPuzzleInputAsList("21"), puzzleDataStore.GetPuzzleAnswer("21", "1"), puzzleDataStore.GetPuzzleAnswer("21", "2"), string.Empty, false),
                new PuzzleData("22", "Actual", puzzleDataStore.GetPuzzleInputAsList("22"), puzzleDataStore.GetPuzzleAnswer("22", "1"), puzzleDataStore.GetPuzzleAnswer("22", "2"), string.Empty, false),
                new PuzzleData("23", "Actual", puzzleDataStore.GetPuzzleInputAsList("23"), puzzleDataStore.GetPuzzleAnswer("23", "1"), puzzleDataStore.GetPuzzleAnswer("23", "2"), string.Empty, false),
                new PuzzleData("24", "Actual", puzzleDataStore.GetPuzzleInputAsList("24"), puzzleDataStore.GetPuzzleAnswer("24", "1"), puzzleDataStore.GetPuzzleAnswer("24", "2"), string.Empty, true),
                new PuzzleData(
                    "08",
                    "Sample",
                    new List<string>()
                    {
                        "nop +0",
                        "acc +1",
                        "jmp +4",
                        "acc +3",
                        "jmp -3",
                        "acc -99",
                        "acc +1",
                        "jmp -4",
                        "acc +6",
                    },
                    "5",
                    string.Empty,
                    string.Empty,
                    false),
                new PuzzleData(
                    "10",
                    "Sample",
                    new List<string>()
                    {
                        "1", "4", "5", "6", "7", "10", "11", "12", "15", "16", "19",
                    },
                    "35",
                    "8",
                    string.Empty,
                    false),
                new PuzzleData(
                    "10",
                    "Sample",
                    new List<string>()
                    {
                        "28", "33", "18", "42", "31", "14", "46", "20", "48", "47", "24", "23", "49", "45", "19", "38", "39", "11", "1", "32", "25", "35", "8", "17", "7", "9", "4", "2", "34", "10", "3",
                    },
                    "220",
                    "19208",
                    string.Empty,
                    false),
                new PuzzleData(
                    "10",
                    "Sample",
                    new List<string>()
                    {
                        "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30",
                    },
                    "30",
                    "53798080",
                    "Test case from Brian",
                    false),
                new PuzzleData(
                    "11",
                    "Sample",
                    new List<string>()
                    {
                        "L.LL.LL.LL",
                        "LLLLLLL.LL",
                        "L.L.L..L..",
                        "LLLL.LL.LL",
                        "L.LL.LL.LL",
                        "L.LLLLL.LL",
                        "..L.L.....",
                        "LLLLLLLLLL",
                        "L.LLLLLL.L",
                        "L.LLLLL.LL",
                    },
                    "37",
                    "26",
                    string.Empty,
                    false),
                new PuzzleData(
                    "12",
                    "Sample",
                    new List<string>()
                    {
                        "F10",
                        "N3",
                        "F7",
                        "R90",
                        "F11",
                    },
                    "25",
                    "286",
                    string.Empty,
                    false),
                new PuzzleData(
                    "13",
                    "Sample",
                    new List<string>()
                    {
                        "939",
                        "7,13,x,x,59,x,31,19",
                    },
                    "295",
                    "1068781",
                    string.Empty,
                    false),
                new PuzzleData(
                    "14",
                    "Sample",
                    new List<string>()
                    {
                        "mask = XXXXXXXXXXXXXXXXXXXXXXXXXXXXX1XXXX0X",
                        "mem[8] = 11",
                        "mem[7] = 101",
                        "mem[8] = 0",
                    },
                    "165",
                    null,
                    string.Empty,
                    false),
                new PuzzleData(
                    "14",
                    "Sample",
                    new List<string>()
                    {
                        "mask = 000000000000000000000000000000X1001X",
                        "mem[42] = 100",
                        "mask = 00000000000000000000000000000000X0XX",
                        "mem[26] = 1",
                    },
                    null,
                    "208",
                    string.Empty,
                    false),
                new PuzzleData(
                    "15",
                    "Sample",
                    new List<string>()
                    {
                        "0,3,6",
                    },
                    "436",
                    "175594",
                    string.Empty,
                    false),
                new PuzzleData(
                    "15",
                    "Sample",
                    new List<string>()
                    {
                        "1,3,2",
                    },
                    "1",
                    "2578",
                    string.Empty,
                    false),
                new PuzzleData(
                    "15",
                    "Sample",
                    new List<string>()
                    {
                        "2,1,3",
                    },
                    "10",
                    "3544142",
                    string.Empty,
                    false),
                new PuzzleData(
                    "15",
                    "Sample",
                    new List<string>()
                    {
                        "1,2,3",
                    },
                    "27",
                    "261214",
                    string.Empty,
                    false),
                new PuzzleData(
                    "15",
                    "Sample",
                    new List<string>()
                    {
                        "2,3,1",
                    },
                    "78",
                    "6895259",
                    string.Empty,
                    false),
                new PuzzleData(
                    "15",
                    "Sample",
                    new List<string>()
                    {
                        "3,2,1",
                    },
                    "438",
                    "18",
                    string.Empty,
                    false),
                new PuzzleData(
                    "15",
                    "Sample",
                    new List<string>()
                    {
                        "3,1,2",
                    },
                    "1836",
                    "362",
                    string.Empty,
                    false),
                new PuzzleData(
                    "16",
                    "Sample",
                    new List<string>()
                    {
                        "class: 1-3 or 5-7",
                        "row: 6-11 or 33-44",
                        "seat: 13-40 or 45-50",
                        string.Empty,
                        "your ticket:",
                        "7,1,14",
                        string.Empty,
                        "nearby tickets:",
                        "7,3,47",
                        "40,4,50",
                        "55,2,20",
                        "38,6,12",
                    },
                    "71",
                    null,
                    string.Empty,
                    false),
                new PuzzleData(
                    "16",
                    "Sample",
                    new List<string>()
                    {
                        "class: 0-1 or 4-19",
                        "row: 0-5 or 8-19",
                        "seat: 0-13 or 16-19",
                        string.Empty,
                        "your ticket:",
                        "11,12,13",
                        string.Empty,
                        "nearby tickets:",
                        "3,9,18",
                        "15,1,5",
                        "5,14,9",
                    },
                    "0",
                    "1",
                    string.Empty,
                    false),
                new PuzzleData(
                    "17",
                    "Sample",
                    new List<string>()
                    {
                        ".#.",
                        "..#",
                        "###",
                    },
                    "112",
                    "848",
                    string.Empty,
                    false),
                new PuzzleData(
                    "19",
                    "Sample",
                    new List<string>()
                    {
                        "42: 9 14 | 10 1",
                        "9: 14 27 | 1 26",
                        "10: 23 14 | 28 1",
                        "1: \"a\"",
                        "11: 42 31",
                        "5: 1 14 | 15 1",
                        "19: 14 1 | 14 14",
                        "12: 24 14 | 19 1",
                        "16: 15 1 | 14 14",
                        "31: 14 17 | 1 13",
                        "6: 14 14 | 1 14",
                        "2: 1 24 | 14 4",
                        "0: 8 11",
                        "13: 14 3 | 1 12",
                        "15: 1 | 14",
                        "17: 14 2 | 1 7",
                        "23: 25 1 | 22 14",
                        "28: 16 1",
                        "4: 1 1",
                        "20: 14 14 | 1 15",
                        "3: 5 14 | 16 1",
                        "27: 1 6 | 14 18",
                        "14: \"b\"",
                        "21: 14 1 | 1 14",
                        "25: 1 1 | 1 14",
                        "22: 14 14",
                        "8: 42",
                        "26: 14 22 | 1 20",
                        "18: 15 15",
                        "7: 14 5 | 1 21",
                        "24: 14 1",
                        string.Empty,
                        "abbbbbabbbaaaababbaabbbbabababbbabbbbbbabaaaa",
                        "bbabbbbaabaabba",
                        "babbbbaabbbbbabbbbbbaabaaabaaa",
                        "aaabbbbbbaaaabaababaabababbabaaabbababababaaa",
                        "bbbbbbbaaaabbbbaaabbabaaa",
                        "bbbababbbbaaaaaaaabbababaaababaabab",
                        "ababaaaaaabaaab",
                        "ababaaaaabbbaba",
                        "baabbaaaabbaaaababbaababb",
                        "abbbbabbbbaaaababbbbbbaaaababb",
                        "aaaaabbaabaaaaababaa",
                        "aaaabbaaaabbaaa",
                        "aaaabbaabbaaaaaaabbbabbbaaabbaabaaa",
                        "babaaabbbaaabaababbaabababaaab",
                        "aabbbbbaabbbaaaaaabbbbbababaaaaabbaaabba",
                    },
                    "3",
                    "12",
                    string.Empty,
                    false),
                new PuzzleData(
                    "20",
                    "Sample",
                    new List<string>()
                    {
                        "Tile 2311:",
                        "..##.#..#.",
                        "##..#.....",
                        "#...##..#.",
                        "####.#...#",
                        "##.##.###.",
                        "##...#.###",
                        ".#.#.#..##",
                        "..#....#..",
                        "###...#.#.",
                        "..###..###",
                        string.Empty,
                        "Tile 1951:",
                        "#.##...##.",
                        "#.####...#",
                        ".....#..##",
                        "#...######",
                        ".##.#....#",
                        ".###.#####",
                        "###.##.##.",
                        ".###....#.",
                        "..#.#..#.#",
                        "#...##.#..",
                        string.Empty,
                        "Tile 1171:",
                        "####...##.",
                        "#..##.#..#",
                        "##.#..#.#.",
                        ".###.####.",
                        "..###.####",
                        ".##....##.",
                        ".#...####.",
                        "#.##.####.",
                        "####..#...",
                        ".....##...",
                        string.Empty,
                        "Tile 1427:",
                        "###.##.#..",
                        ".#..#.##..",
                        ".#.##.#..#",
                        "#.#.#.##.#",
                        "....#...##",
                        "...##..##.",
                        "...#.#####",
                        ".#.####.#.",
                        "..#..###.#",
                        "..##.#..#.",
                        string.Empty,
                        "Tile 1489:",
                        "##.#.#....",
                        "..##...#..",
                        ".##..##...",
                        "..#...#...",
                        "#####...#.",
                        "#..#.#.#.#",
                        "...#.#.#..",
                        "##.#...##.",
                        "..##.##.##",
                        "###.##.#..",
                        string.Empty,
                        "Tile 2473:",
                        "#....####.",
                        "#..#.##...",
                        "#.##..#...",
                        "######.#.#",
                        ".#...#.#.#",
                        ".#########",
                        ".###.#..#.",
                        "########.#",
                        "##...##.#.",
                        "..###.#.#.",
                        string.Empty,
                        "Tile 2971:",
                        "..#.#....#",
                        "#...###...",
                        "#.#.###...",
                        "##.##..#..",
                        ".#####..##",
                        ".#..####.#",
                        "#..#.#..#.",
                        "..####.###",
                        "..#.#.###.",
                        "...#.#.#.#",
                        string.Empty,
                        "Tile 2729:",
                        "...#.#.#.#",
                        "####.#....",
                        "..#.#.....",
                        "....#..#.#",
                        ".##..##.#.",
                        ".#.####...",
                        "####.#.#..",
                        "##.####...",
                        "##..#.##..",
                        "#.##...##.",
                        string.Empty,
                        "Tile 3079:",
                        "#.#.#####.",
                        ".#..######",
                        "..#.......",
                        "######....",
                        "####.#..#.",
                        ".#...#.##.",
                        "#.#####.##",
                        "..#.###...",
                        "..#.......",
                        "..#.###...",
                        string.Empty,
                    },
                    "20899048083289",
                    "273",
                    string.Empty,
                    false),
                new PuzzleData(
                    "21",
                    "Sample",
                    new List<string>()
                    {
                        "mxmxvkd kfcds sqjhc nhms (contains dairy, fish)",
                        "trh fvjkl sbzzf mxmxvkd (contains dairy)",
                        "sqjhc fvjkl (contains soy)",
                        "sqjhc mxmxvkd sbzzf (contains fish)",
                    },
                    "5",
                    "mxmxvkd,sqjhc,fvjkl",
                    string.Empty,
                    false),
                new PuzzleData(
                    "22",
                    "Sample",
                    new List<string>()
                    {
                        "Player 1:",
                        "9",
                        "2",
                        "6",
                        "3",
                        "1",
                        string.Empty,
                        "Player 2:",
                        "5",
                        "8",
                        "4",
                        "7",
                        "10",
                    },
                    "306",
                    "291",
                    string.Empty,
                    false),
                new PuzzleData(
                    "23",
                    "Sample",
                    new List<string>()
                    {
                        "389125467",
                    },
                    "67384529",
                    null, // "62466204",
                    string.Empty,
                    false),
                new PuzzleData(
                    "24",
                    "Sample",
                    new List<string>()
                    {
                        "sesenwnenenewseeswwswswwnenewsewsw",
                        "neeenesenwnwwswnenewnwwsewnenwseswesw",
                        "seswneswswsenwwnwse",
                        "nwnwneseeswswnenewneswwnewseswneseene",
                        "swweswneswnenwsewnwneneseenw",
                        "eesenwseswswnenwswnwnwsewwnwsene",
                        "sewnenenenesenwsewnenwwwse",
                        "wenwwweseeeweswwwnwwe",
                        "wsweesenenewnwwnwsenewsenwwsesesenwne",
                        "neeswseenwwswnwswswnw",
                        "nenwswwsewswnenenewsenwsenwnesesenew",
                        "enewnwewneswsewnwswenweswnenwsenwsw",
                        "sweneswneswneneenwnewenewwneswswnese",
                        "swwesenesewenwneswnwwneseswwne",
                        "enesenwswwswneneswsenwnewswseenwsese",
                        "wnwnesenesenenwwnenwsewesewsesesew",
                        "nenewswnwewswnenesenwnesewesw",
                        "eneswnwswnwsenenwnwnwwseeswneewsenese",
                        "neswnwewnwnwseenwseesewsenwsweewe",
                        "wseweeenwnesenwwwswnew",
                    },
                    "10",
                    "2208",
                    string.Empty,
                    true),
            };
        }

        public List<PuzzleData> GetPuzzleData()
        {
            return _puzzleData.Where(x => x.Enabled).OrderBy(x => (x.Day, (x.Type == "Actual") ? 2 : 1)).ToList();
        }
    }
}