//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2020.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2020.Utilities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1883
        ///1543
        ///1801
        ///1731
        ///1070
        ///1631
        ///1490
        ///1179
        ///1098
        ///1582
        ///1717
        ///1830
        ///1408
        ///1524
        ///889
        ///985
        ///2005
        ///1540
        ///1085
        ///1607
        ///1518
        ///1993
        ///1496
        ///1537
        ///1514
        ///1719
        ///1218
        ///1420
        ///1027
        ///1339
        ///1430
        ///989
        ///1613
        ///1970
        ///1227
        ///1082
        ///1079
        ///1068
        ///1674
        ///1186
        ///1744
        ///1297
        ///1467
        ///1647
        ///1141
        ///1825
        ///1759
        ///1395
        ///1596
        ///1405
        ///1844
        ///1461
        ///1762
        ///1122
        ///1173
        ///1838
        ///1983
        ///1632
        ///1995
        ///1245
        ///1454
        ///1120
        ///1671
        ///1526
        ///1572
        ///1929
        ///1642
        ///1864
        ///1351
        ///1155
        ///1885
        ///1226
        ///1810
        ///1252
        ///1061
        ///1882
        ///2002
        ///1627
        ///1128
        ///1575
        ///1750
        ///1046
        ///1767
        ///1270
        ///1037
        ///1198        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01_PuzzleInput {
            get {
                return ResourceManager.GetString("Day01_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 935419.
        /// </summary>
        internal static string Day01Part1_Answer {
            get {
                return ResourceManager.GetString("Day01Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49880012.
        /// </summary>
        internal static string Day01Part2_Answer {
            get {
                return ResourceManager.GetString("Day01Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-13 r: gqdrspndrpsrjfjx
        ///5-16 j: jjjjkjjzjjjjjfjzjjj
        ///14-16 r: rrrnrrrrrcnrgxrr
        ///1-3 k: bkktwhgktv
        ///3-5 q: dxqqqzmqvs
        ///11-14 s: sssssssssssssv
        ///1-3 d: cdzdq
        ///13-16 q: scdqpdgpkvbwwqbv
        ///9-10 d: ddrdddlddd
        ///15-17 v: jvvvvvvgcvvvvrcvnv
        ///2-3 s: xssx
        ///8-15 j: jwjjjjkhjjjltjmjjjr
        ///7-15 m: wqspfmtpjftmplwp
        ///1-11 s: swdgzhgsxtssndzfm
        ///3-4 b: bgjrg
        ///1-12 x: jxgxxxpjwpsht
        ///5-15 x: xxjxwshpxjxxxxsnxvz
        ///4-11 r: bjnrpswfprrng
        ///12-14 j: wjjzmwnmmvzsjhnnkj
        ///3-4 d: dddv
        ///2-4 b: bfxx
        ///15-16 r: rrrrrrrrrrrlrrphrr
        ///6-11 j: j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02_PuzzleInput {
            get {
                return ResourceManager.GetString("Day02_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        internal static string Day02Part1_Answer {
            get {
                return ResourceManager.GetString("Day02Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 245.
        /// </summary>
        internal static string Day02Part2_Answer {
            get {
                return ResourceManager.GetString("Day02Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..#..#......###.#...#......#..#
        ///...#.....#...#...#..........#..
        ///....#.#...............#.#.#....
        ///.........#.......##............
        ///#.#....#.#####.##.#........#..#
        ///.....#...##.#..#.##...#.#..#...
        ///#.#..###.#........#....##...#.#
        ///..###.....#..###.....##........
        ///#.#.#...........#.....#.#....##
        ///...#.#.##.##.#.#......#...##.#.
        ///.....##.#..#....#..#...##...###
        ///...#.....#..#..#...#.#....##...
        ///.#...##.#.........#...#.#......
        ///....#...#.....#......#...#.....
        ///.#...#.....#....#......#...#...
        ///#...#......####.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03_PuzzleInput {
            get {
                return ResourceManager.GetString("Day03_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 292.
        /// </summary>
        internal static string Day03Part1_Answer {
            get {
                return ResourceManager.GetString("Day03Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9354744432.
        /// </summary>
        internal static string Day03Part2_Answer {
            get {
                return ResourceManager.GetString("Day03Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hgt:159cm
        ///pid:561068005 eyr:2025 iyr:2017 cid:139 ecl:blu hcl:#ceb3a1
        ///byr:1940
        ///
        ///iyr:2014
        ///byr:1986 pid:960679613 eyr:2025 ecl:hzl
        ///
        ///cid:211 ecl:blu hcl:#7d3b0c iyr:2011 pid:006632702
        ///byr:1982 eyr:2023 hgt:68in
        ///
        ///hcl:#341e13 hgt:192 iyr:2028
        ///ecl:utc
        ///eyr:2027 byr:1979 pid:653515689
        ///
        ///eyr:2026 hgt:161cm ecl:#1850b8
        ///pid:298779494 hcl:b2114e iyr:1953
        ///
        ///hgt:155cm
        ///hcl:#a97842 iyr:2019
        ///ecl:gry byr:1939
        ///pid:935099157 eyr:2027
        ///
        ///eyr:2024 ecl:grn
        ///pid:102781360 byr:1962 iyr:2013 hcl:#602927
        ///
        ///hcl:#602 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04_PuzzleInput {
            get {
                return ResourceManager.GetString("Day04_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 202.
        /// </summary>
        internal static string Day04Part1_Answer {
            get {
                return ResourceManager.GetString("Day04Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 137.
        /// </summary>
        internal static string Day04Part2_Answer {
            get {
                return ResourceManager.GetString("Day04Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFBBFFFLLL
        ///BFBFBFBLLR
        ///BFFBBBBRRR
        ///FBFBFFFLLL
        ///FFFBFBBRRL
        ///FBBFFBBLLR
        ///FBBBFBFRRR
        ///FBFBBFFLLL
        ///FBFBFBFRRR
        ///FFBFFFFLRL
        ///FBFBFBBLRL
        ///FBFFFBBLLR
        ///FBBBBBFLLL
        ///BBFBFFFLLL
        ///FBBBBFBLRL
        ///FBBBBFBRRR
        ///FBFFBBBLLL
        ///FBFFFFFLLR
        ///BFBFFFFRRL
        ///BFFFBBBLRL
        ///FBBBBFBRLL
        ///BFBFBBBRLR
        ///BFBBFFFLRR
        ///BBFFFFBRRR
        ///FFBFBBFRRR
        ///FFBFBFBLRR
        ///BBFBBFBRRL
        ///BBFBFBFLRR
        ///FBBBBFFLRR
        ///BFBFBBBLRL
        ///BFBFFFFRLL
        ///BBFFFBFRLR
        ///BBFFFBBLRR
        ///FBFBBBFRRL
        ///BFBFBBFLRL
        ///BBFFBBBRLL
        ///BBFFBBBLRL
        ///FBFFFFFRLR
        ///FBFBFBFRRL
        ///FBBFBFBLLR
        ///BFBBFFBLLL
        ///BFFFFBFRLR
        ///FBBFFFFL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05_PuzzleInput {
            get {
                return ResourceManager.GetString("Day05_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 890.
        /// </summary>
        internal static string Day05Part1_Answer {
            get {
                return ResourceManager.GetString("Day05Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 651.
        /// </summary>
        internal static string Day05Part2_Answer {
            get {
                return ResourceManager.GetString("Day05Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psyjxulrdtfe
        ///jeusdrlxyftp
        ///ufdpjsxrlztye
        ///yeorabxsdnhftujlp
        ///pedfxtsryujl
        ///
        ///tauc
        ///bauptcr
        ///uact
        ///cuat
        ///tacu
        ///
        ///xyadvrniqso
        ///mquglwtczhvpnb
        ///bmfnuqkvz
        ///
        ///fzynq
        ///yqznf
        ///qfynz
        ///zfnqy
        ///
        ///kisfzpdjecowv
        ///rkivjpqwomzsced
        ///
        ///prjbzgwkhoqcyxvnd
        ///vfsietlaqmu
        ///
        ///jucif
        ///cukfsji
        ///jicduf
        ///ficuhj
        ///cfjiu
        ///
        ///netxwkjlgmv
        ///nxjkgdvle
        ///nxhbylvqjek
        ///
        ///ejpfqsc
        ///rvewqcpsjmond
        ///ejspcq
        ///qsecjp
        ///
        ///i
        ///mc
        ///s
        ///s
        ///
        ///kbem
        ///eqh
        ///ep
        ///ehfp
        ///
        ///fgjmp
        ///jgoac
        ///
        ///hrulfeqm
        ///rlmfeqc
        ///lerfmjbq
        ///lebmqsrf
        ///zxflemqdirkya
        ///
        ///zlhc
        ///lhv
        ///lcvgh
        ///hlrq
        ///
        ///x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06_PuzzleInput {
            get {
                return ResourceManager.GetString("Day06_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6686.
        /// </summary>
        internal static string Day06Part1_Answer {
            get {
                return ResourceManager.GetString("Day06Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3476.
        /// </summary>
        internal static string Day06Part2_Answer {
            get {
                return ResourceManager.GetString("Day06Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark orange bags contain 3 dark chartreuse bags.
        ///striped fuchsia bags contain 5 striped lavender bags.
        ///dull gray bags contain 4 muted cyan bags, 3 light maroon bags.
        ///dull chartreuse bags contain 3 light tan bags, 3 dotted bronze bags, 4 dark crimson bags, 4 dull gold bags.
        ///shiny teal bags contain 3 muted maroon bags, 1 bright salmon bag, 2 dark chartreuse bags.
        ///dull crimson bags contain 1 clear cyan bag, 1 dark chartreuse bag, 1 drab gold bag, 1 dim black bag.
        ///plaid silver bags contain 2 muted bronze  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07_PuzzleInput {
            get {
                return ResourceManager.GetString("Day07_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 213.
        /// </summary>
        internal static string Day07Part1_Answer {
            get {
                return ResourceManager.GetString("Day07Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38426.
        /// </summary>
        internal static string Day07Part2_Answer {
            get {
                return ResourceManager.GetString("Day07Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jmp +336
        ///jmp +593
        ///jmp +121
        ///acc -8
        ///nop +459
        ///jmp +451
        ///acc -6
        ///acc +23
        ///acc +23
        ///acc -2
        ///jmp +113
        ///acc -11
        ///acc +25
        ///jmp +529
        ///acc +0
        ///jmp +1
        ///jmp +313
        ///acc +30
        ///nop +235
        ///jmp +45
        ///nop +195
        ///acc -11
        ///jmp +491
        ///acc +6
        ///nop +425
        ///nop +68
        ///acc +9
        ///jmp -25
        ///jmp +507
        ///jmp +456
        ///acc -1
        ///acc +49
        ///acc +5
        ///jmp +31
        ///acc +30
        ///nop +513
        ///jmp +499
        ///nop +533
        ///acc +18
        ///acc +28
        ///acc -2
        ///jmp +170
        ///acc -5
        ///jmp +180
        ///nop +179
        ///acc +15
        ///acc +33
        ///nop +27
        ///jmp +424
        ///acc +30
        ///acc +33
        ///acc +50
        ///jmp +348
        ///jmp +435
        ///acc +21
        ///acc + [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08_PuzzleInput {
            get {
                return ResourceManager.GetString("Day08_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1766.
        /// </summary>
        internal static string Day08Part1_Answer {
            get {
                return ResourceManager.GetString("Day08Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1639.
        /// </summary>
        internal static string Day08Part2_Answer {
            get {
                return ResourceManager.GetString("Day08Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30
        ///16
        ///33
        ///40
        ///41
        ///25
        ///2
        ///29
        ///37
        ///4
        ///11
        ///1
        ///42
        ///10
        ///21
        ///13
        ///48
        ///28
        ///19
        ///5
        ///46
        ///49
        ///24
        ///8
        ///34
        ///3
        ///6
        ///30
        ///7
        ///22
        ///9
        ///12
        ///14
        ///15
        ///16
        ///27
        ///4
        ///11
        ///60
        ///10
        ///17
        ///56
        ///13
        ///18
        ///19
        ///20
        ///21
        ///23
        ///29
        ///24
        ///25
        ///39
        ///47
        ///71
        ///34
        ///22
        ///26
        ///28
        ///30
        ///14
        ///15
        ///27
        ///31
        ///32
        ///35
        ///38
        ///37
        ///48
        ///33
        ///36
        ///40
        ///64
        ///41
        ///66
        ///49
        ///42
        ///58
        ///45
        ///83
        ///29
        ///75
        ///60
        ///44
        ///51
        ///53
        ///46
        ///68
        ///69
        ///70
        ///62
        ///113
        ///65
        ///71
        ///76
        ///95
        ///73
        ///74
        ///78
        ///139
        ///86
        ///106
        ///80
        ///82
        ///89
        ///119
        ///112
        ///90
        ///133
        ///159
        ///99
        ///127
        ///140
        ///147
        ///169
        ///135
        ///136
        ///212
        ///144
        ///149
        ///160
        ///208
        ///188
        ///222
        ///162
        ///166
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09_PuzzleInput {
            get {
                return ResourceManager.GetString("Day09_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14144619.
        /// </summary>
        internal static string Day09Part1_Answer {
            get {
                return ResourceManager.GetString("Day09Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1766397.
        /// </summary>
        internal static string Day09Part2_Answer {
            get {
                return ResourceManager.GetString("Day09Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47
        ///99
        ///115
        ///65
        ///10
        ///55
        ///19
        ///73
        ///80
        ///100
        ///71
        ///110
        ///64
        ///135
        ///49
        ///3
        ///1
        ///98
        ///132
        ///2
        ///38
        ///118
        ///66
        ///116
        ///104
        ///87
        ///79
        ///114
        ///40
        ///37
        ///44
        ///97
        ///4
        ///140
        ///60
        ///86
        ///56
        ///133
        ///7
        ///146
        ///85
        ///111
        ///134
        ///53
        ///121
        ///77
        ///117
        ///21
        ///12
        ///81
        ///145
        ///129
        ///107
        ///93
        ///22
        ///48
        ///11
        ///54
        ///92
        ///78
        ///67
        ///20
        ///138
        ///125
        ///57
        ///96
        ///26
        ///147
        ///124
        ///34
        ///74
        ///143
        ///13
        ///28
        ///126
        ///50
        ///29
        ///70
        ///39
        ///63
        ///41
        ///91
        ///32
        ///84
        ///144
        ///27
        ///139
        ///33
        ///88
        ///72
        ///23
        ///103
        ///16.
        /// </summary>
        internal static string Day10_PuzzleInput {
            get {
                return ResourceManager.GetString("Day10_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1848.
        /// </summary>
        internal static string Day10Part1_Answer {
            get {
                return ResourceManager.GetString("Day10Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8099130339328.
        /// </summary>
        internal static string Day10Part2_Answer {
            get {
                return ResourceManager.GetString("Day10Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLLLLL.LLLL.LLLLL.LLLLLLLLLLLLLL.LLLLLLLLLLLLLL.LLLLL.LLLLLLLLLLLLLL.LLLLLLL.LLLLLL.LLLLLLLLLL.L
        ///LLLLLLLLLLLLLLLLLLL.L.LL.LLL.LLLLL.LLLLLLLLLLL.LL.LLLLL.LLLLLLLL.LLLLLLLLL.LLL.LLLLLLLLLLLLLLLLLLL
        ///LLLLLLLLLLLLL.LLLLLLLLLLLLLL.LL.LL.LLLLLLL.LLLLLL.LLLLLLLLL.LLLL.LLLLL.LLLLLLL.LLLLLL.LLLLLLLLLLLL
        ///LLLLLLLL.LLLL.LLLLL..LLLLLLL.L.LLL.LLLLLLL.LLLLLL.LLLLL.LLLLLLLL.LLLLLLLLLLLLL.LLLLLL.LLLLLLLLLLLL
        ///LLLLLL.L.LLLL.L.LLL.LLLLLLLLLLLLLL.LLL.LLL.LLLLLL.LLLLL.LLLLLLLLLLLLLL.LLLLLLL.LLLLLL.LLLLLLLLLLLL
        ///LLLLLLLL.LLL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11_PuzzleInput {
            get {
                return ResourceManager.GetString("Day11_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2412.
        /// </summary>
        internal static string Day11Part1_Answer {
            get {
                return ResourceManager.GetString("Day11Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data2.
        /// </summary>
        internal static string Day11Part2_Answer {
            get {
                return ResourceManager.GetString("Day11Part2_Answer", resourceCulture);
            }
        }
    }
}
