//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2020.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2020.Utilities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1883
        ///1543
        ///1801
        ///1731
        ///1070
        ///1631
        ///1490
        ///1179
        ///1098
        ///1582
        ///1717
        ///1830
        ///1408
        ///1524
        ///889
        ///985
        ///2005
        ///1540
        ///1085
        ///1607
        ///1518
        ///1993
        ///1496
        ///1537
        ///1514
        ///1719
        ///1218
        ///1420
        ///1027
        ///1339
        ///1430
        ///989
        ///1613
        ///1970
        ///1227
        ///1082
        ///1079
        ///1068
        ///1674
        ///1186
        ///1744
        ///1297
        ///1467
        ///1647
        ///1141
        ///1825
        ///1759
        ///1395
        ///1596
        ///1405
        ///1844
        ///1461
        ///1762
        ///1122
        ///1173
        ///1838
        ///1983
        ///1632
        ///1995
        ///1245
        ///1454
        ///1120
        ///1671
        ///1526
        ///1572
        ///1929
        ///1642
        ///1864
        ///1351
        ///1155
        ///1885
        ///1226
        ///1810
        ///1252
        ///1061
        ///1882
        ///2002
        ///1627
        ///1128
        ///1575
        ///1750
        ///1046
        ///1767
        ///1270
        ///1037
        ///1198        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01_PuzzleInput {
            get {
                return ResourceManager.GetString("Day01_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 935419.
        /// </summary>
        internal static string Day01Part1_Answer {
            get {
                return ResourceManager.GetString("Day01Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49880012.
        /// </summary>
        internal static string Day01Part2_Answer {
            get {
                return ResourceManager.GetString("Day01Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-13 r: gqdrspndrpsrjfjx
        ///5-16 j: jjjjkjjzjjjjjfjzjjj
        ///14-16 r: rrrnrrrrrcnrgxrr
        ///1-3 k: bkktwhgktv
        ///3-5 q: dxqqqzmqvs
        ///11-14 s: sssssssssssssv
        ///1-3 d: cdzdq
        ///13-16 q: scdqpdgpkvbwwqbv
        ///9-10 d: ddrdddlddd
        ///15-17 v: jvvvvvvgcvvvvrcvnv
        ///2-3 s: xssx
        ///8-15 j: jwjjjjkhjjjltjmjjjr
        ///7-15 m: wqspfmtpjftmplwp
        ///1-11 s: swdgzhgsxtssndzfm
        ///3-4 b: bgjrg
        ///1-12 x: jxgxxxpjwpsht
        ///5-15 x: xxjxwshpxjxxxxsnxvz
        ///4-11 r: bjnrpswfprrng
        ///12-14 j: wjjzmwnmmvzsjhnnkj
        ///3-4 d: dddv
        ///2-4 b: bfxx
        ///15-16 r: rrrrrrrrrrrlrrphrr
        ///6-11 j: j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02_PuzzleInput {
            get {
                return ResourceManager.GetString("Day02_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        internal static string Day02Part1_Answer {
            get {
                return ResourceManager.GetString("Day02Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 245.
        /// </summary>
        internal static string Day02Part2_Answer {
            get {
                return ResourceManager.GetString("Day02Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..#..#......###.#...#......#..#
        ///...#.....#...#...#..........#..
        ///....#.#...............#.#.#....
        ///.........#.......##............
        ///#.#....#.#####.##.#........#..#
        ///.....#...##.#..#.##...#.#..#...
        ///#.#..###.#........#....##...#.#
        ///..###.....#..###.....##........
        ///#.#.#...........#.....#.#....##
        ///...#.#.##.##.#.#......#...##.#.
        ///.....##.#..#....#..#...##...###
        ///...#.....#..#..#...#.#....##...
        ///.#...##.#.........#...#.#......
        ///....#...#.....#......#...#.....
        ///.#...#.....#....#......#...#...
        ///#...#......####.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03_PuzzleInput {
            get {
                return ResourceManager.GetString("Day03_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 292.
        /// </summary>
        internal static string Day03Part1_Answer {
            get {
                return ResourceManager.GetString("Day03Part1_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9354744432.
        /// </summary>
        internal static string Day03Part2_Answer {
            get {
                return ResourceManager.GetString("Day03Part2_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hgt:159cm
        ///pid:561068005 eyr:2025 iyr:2017 cid:139 ecl:blu hcl:#ceb3a1
        ///byr:1940
        ///
        ///iyr:2014
        ///byr:1986 pid:960679613 eyr:2025 ecl:hzl
        ///
        ///cid:211 ecl:blu hcl:#7d3b0c iyr:2011 pid:006632702
        ///byr:1982 eyr:2023 hgt:68in
        ///
        ///hcl:#341e13 hgt:192 iyr:2028
        ///ecl:utc
        ///eyr:2027 byr:1979 pid:653515689
        ///
        ///eyr:2026 hgt:161cm ecl:#1850b8
        ///pid:298779494 hcl:b2114e iyr:1953
        ///
        ///hgt:155cm
        ///hcl:#a97842 iyr:2019
        ///ecl:gry byr:1939
        ///pid:935099157 eyr:2027
        ///
        ///eyr:2024 ecl:grn
        ///pid:102781360 byr:1962 iyr:2013 hcl:#602927
        ///
        ///hcl:#602 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04_PuzzleInput {
            get {
                return ResourceManager.GetString("Day04_PuzzleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 202.
        /// </summary>
        internal static string Day04Part1_Answer {
            get {
                return ResourceManager.GetString("Day04Part1_Answer", resourceCulture);
            }
        }
    }
}
